### ISSUE TITLE
Rename $r to something more descriptive

### ISSUE THREAD

**Issue by Jaden-Giordano** [crishellco/vue-request-store#1]
`$r` doesn't really make sense here, maybe `$requests` would be better. I'm not sure of any naming standards the Vue community follows for things like these but most I've used have always used descriptive names (i.e. [vue-apollo](https://github.com/Akryum/vue-apollo) uses `$apollo` and [vue-router](https://github.com/vuejs/vue-router) uses `$router` and `$route`).

**Comment by crishellco** [comment]
Good suggestion, @Jaden-Giordano.

You can now use `vm.$r` or `vm.$requests`, although only the latter is listed in the documentation. See [v0.2.0](https://www.npmjs.com/package/vue-request-store/v/0.2.0).
